---

controller:
  ingressClassResource:
    # -- Name of the ingressClass
    name: external-nginx
  admissionWebhooks:
    enabled: false
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
#Required for ACME
  watchIngressWithoutClass: true
  extraArgs:
   ingress-class: external-nginx
